# Generated by Django 3.1.7 on 2021-08-31 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabled', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('userid', models.CharField(default=False, max_length=30)),
                ('phone_number', models.CharField(default=False, max_length=30)),
                ('data_used', models.CharField(default=False, max_length=30)),
                ('lifetime', models.BooleanField(default=False)),
                ('auto_disable', models.BooleanField(default=False)),
                ('user_name', models.CharField(default=False, max_length=30)),
                ('send', models.CharField(default=False, max_length=30)),
                ('chrome_ext_dis', models.BooleanField(default=False)),
                ('chrome_bot_dis', models.BooleanField(default=False)),
                ('firefox_ext_dis', models.BooleanField(default=False)),
                ('firefox_bot_dis', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
